# Generated by Django 3.2.9 on 2021-12-08 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstOder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(choices=[('HG', 'High School'), ('CL', 'College'), ('UG', 'Undergraduate'), ('MS', 'Masters'), ('PHD', 'PhD')], max_length=100)),
                ('type_of_work', models.CharField(choices=[('AE', 'Admission Essay'), ('Bio', 'Biographies'), ('BP', 'Business Plan'), ('BR', 'Book Review')], max_length=100)),
                ('deadline', models.CharField(choices=[('14D', '14 Days'), ('10D', '10 Days'), ('7D', '7 Days'), ('6D', '6 Days'), ('5D', '5 Days'), ('4D', '4 Days'), ('3D', '3 Days'), ('2D', '2 Days'), ('1D', '1 Days'), ('20H', '20 Hours'), ('16H', '16 Hours'), ('12H', '12 Hours'), ('8H', '8 Hours'), ('6H', '6 Hours'), ('5H', '5 Hours'), ('3H', '3 Hours'), ('2H', '2 Hours')], max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondOder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('OT', 'Other'), ('ACC', 'Account'), ('CL', 'Criminal Law')], max_length=100)),
                ('number_of_pages', models.CharField(max_length=300)),
                ('double_spaced', models.BooleanField(default=False)),
                ('reference_style', models.CharField(choices=[('H', 'Harvard'), ('A', 'APA'), ('M', 'MLA'), ('C', 'Chicago'), ('V', 'Vancouver')], max_length=100)),
                ('reference_total', models.IntegerField(default=1)),
                ('oder_instruction', models.TextField()),
                ('additional_materials', models.FileField(upload_to='media/')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=7)),
                ('oder_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.firstoder')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_task', models.CharField(choices=[('PPT', 'PowerPoint'), ('PS', 'PhotoShop'), ('IG', 'InfoGraph'), ('WB', 'Web Design')], max_length=100)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
