# Generated by Django 3.2.9 on 2021-12-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondoder',
            old_name='oder_form',
            new_name='order_form',
        ),
    ]
