# Generated by Django 3.2.9 on 2021-12-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20211208_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondorder',
            old_name='oder_instruction',
            new_name='order_instruction',
        ),
    ]
