# Generated by Django 3.2.9 on 2021-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_rename_oder_instruction_secondorder_order_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondorder',
            name='additional_materials',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='secondorder',
            name='order_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
